CC = gcc
CFLAGS = -lpthread -g
EXEC = bad_list safe_list better_list granular_list

all: $(EXEC)

bad_list: bad_list.c
safe_list: safe_list.c
better_list: better_list.c
granular_list: granular_list.c

clean:

spotless: clean
	-rm $(EXEC)
